/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BatchRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batches"
      | "getBatchByUnit"
      | "registerBatch"
      | "roleManager"
      | "serializeUnit"
      | "setBatchStatus"
      | "unitToBatch"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchRegistered"
      | "BatchStatusUpdated"
      | "UnitSerialized"
  ): EventFragment;

  encodeFunctionData(functionFragment: "batches", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBatchByUnit",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerBatch",
    values: [BytesLike, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "serializeUnit",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBatchStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unitToBatch",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBatchByUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBatchStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unitToBatch",
    data: BytesLike
  ): Result;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    batchId: BytesLike,
    manufacturer: AddressLike,
    medicineName: string,
    totalQuantity: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    manufacturer: string,
    medicineName: string,
    totalQuantity: bigint
  ];
  export interface OutputObject {
    batchId: string;
    manufacturer: string;
    medicineName: string;
    totalQuantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchStatusUpdatedEvent {
  export type InputTuple = [batchId: BytesLike, status: BigNumberish];
  export type OutputTuple = [batchId: string, status: bigint];
  export interface OutputObject {
    batchId: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnitSerializedEvent {
  export type InputTuple = [
    unitId: BytesLike,
    batchId: BytesLike,
    serialNumber: BigNumberish
  ];
  export type OutputTuple = [
    unitId: string,
    batchId: string,
    serialNumber: bigint
  ];
  export interface OutputObject {
    unitId: string;
    batchId: string;
    serialNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BatchRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BatchRegistry;
  waitForDeployment(): Promise<this>;

  interface: BatchRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        batchId: string;
        medicineName: string;
        manufacturer: string;
        manufactureDate: bigint;
        expiryDate: bigint;
        totalQuantity: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getBatchByUnit: TypedContractMethod<[unitId: BytesLike], [string], "view">;

  registerBatch: TypedContractMethod<
    [
      batchId: BytesLike,
      medicineName: string,
      manufactureDate: BigNumberish,
      expiryDate: BigNumberish,
      totalQuantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  serializeUnit: TypedContractMethod<
    [batchId: BytesLike, unitId: BytesLike, serialNumber: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBatchStatus: TypedContractMethod<
    [batchId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  unitToBatch: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        batchId: string;
        medicineName: string;
        manufacturer: string;
        manufactureDate: bigint;
        expiryDate: bigint;
        totalQuantity: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatchByUnit"
  ): TypedContractMethod<[unitId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerBatch"
  ): TypedContractMethod<
    [
      batchId: BytesLike,
      medicineName: string,
      manufactureDate: BigNumberish,
      expiryDate: BigNumberish,
      totalQuantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "serializeUnit"
  ): TypedContractMethod<
    [batchId: BytesLike, unitId: BytesLike, serialNumber: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBatchStatus"
  ): TypedContractMethod<
    [batchId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unitToBatch"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getEvent(
    key: "BatchRegistered"
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "BatchStatusUpdated"
  ): TypedContractEvent<
    BatchStatusUpdatedEvent.InputTuple,
    BatchStatusUpdatedEvent.OutputTuple,
    BatchStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UnitSerialized"
  ): TypedContractEvent<
    UnitSerializedEvent.InputTuple,
    UnitSerializedEvent.OutputTuple,
    UnitSerializedEvent.OutputObject
  >;

  filters: {
    "BatchRegistered(bytes32,address,string,uint256)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "BatchStatusUpdated(bytes32,uint8)": TypedContractEvent<
      BatchStatusUpdatedEvent.InputTuple,
      BatchStatusUpdatedEvent.OutputTuple,
      BatchStatusUpdatedEvent.OutputObject
    >;
    BatchStatusUpdated: TypedContractEvent<
      BatchStatusUpdatedEvent.InputTuple,
      BatchStatusUpdatedEvent.OutputTuple,
      BatchStatusUpdatedEvent.OutputObject
    >;

    "UnitSerialized(bytes32,bytes32,uint32)": TypedContractEvent<
      UnitSerializedEvent.InputTuple,
      UnitSerializedEvent.OutputTuple,
      UnitSerializedEvent.OutputObject
    >;
    UnitSerialized: TypedContractEvent<
      UnitSerializedEvent.InputTuple,
      UnitSerializedEvent.OutputTuple,
      UnitSerializedEvent.OutputObject
    >;
  };
}
