/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SaleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "finalizeSale" | "roleManager" | "sales"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SaleFinalized"): EventFragment;

  encodeFunctionData(
    functionFragment: "finalizeSale",
    values: [BytesLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sales", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "finalizeSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sales", data: BytesLike): Result;
}

export namespace SaleFinalizedEvent {
  export type InputTuple = [
    unitId: BytesLike,
    pharmacy: AddressLike,
    buyer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    unitId: string,
    pharmacy: string,
    buyer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    unitId: string;
    pharmacy: string;
    buyer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SaleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SaleRegistry;
  waitForDeployment(): Promise<this>;

  interface: SaleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  finalizeSale: TypedContractMethod<
    [
      unitId: BytesLike,
      buyer: AddressLike,
      pharmacySig: BytesLike,
      buyerSig: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  sales: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string, string] & {
        unitId: string;
        pharmacy: string;
        buyer: string;
        timestamp: bigint;
        pharmacySig: string;
        buyerSig: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "finalizeSale"
  ): TypedContractMethod<
    [
      unitId: BytesLike,
      buyer: AddressLike,
      pharmacySig: BytesLike,
      buyerSig: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sales"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string, string] & {
        unitId: string;
        pharmacy: string;
        buyer: string;
        timestamp: bigint;
        pharmacySig: string;
        buyerSig: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "SaleFinalized"
  ): TypedContractEvent<
    SaleFinalizedEvent.InputTuple,
    SaleFinalizedEvent.OutputTuple,
    SaleFinalizedEvent.OutputObject
  >;

  filters: {
    "SaleFinalized(bytes32,address,address,uint64)": TypedContractEvent<
      SaleFinalizedEvent.InputTuple,
      SaleFinalizedEvent.OutputTuple,
      SaleFinalizedEvent.OutputObject
    >;
    SaleFinalized: TypedContractEvent<
      SaleFinalizedEvent.InputTuple,
      SaleFinalizedEvent.OutputTuple,
      SaleFinalizedEvent.OutputObject
    >;
  };
}
