/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ShipmentLedger {
  export type SupplyEventStruct = {
    unitId: BytesLike;
    eventType: BigNumberish;
    actor: AddressLike;
    timestamp: BigNumberish;
    locationHash: BytesLike;
    senderConfirmed: boolean;
    receiverConfirmed: boolean;
  };

  export type SupplyEventStructOutput = [
    unitId: string,
    eventType: bigint,
    actor: string,
    timestamp: bigint,
    locationHash: string,
    senderConfirmed: boolean,
    receiverConfirmed: boolean
  ] & {
    unitId: string;
    eventType: bigint;
    actor: string;
    timestamp: bigint;
    locationHash: string;
    senderConfirmed: boolean;
    receiverConfirmed: boolean;
  };
}

export interface ShipmentLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveShipment"
      | "confirmDelivery"
      | "dispatchShipment"
      | "getUnitEvents"
      | "recordSupplyEvent"
      | "requestShipment"
      | "roleManager"
      | "shipments"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ShipmentApproved"
      | "ShipmentDelivered"
      | "ShipmentDispatched"
      | "ShipmentRequested"
      | "SupplyEventRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveShipment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatchShipment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnitEvents",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSupplyEvent",
    values: [BytesLike, BigNumberish, BytesLike, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "requestShipment",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "shipments",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveShipment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dispatchShipment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnitEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSupplyEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestShipment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shipments", data: BytesLike): Result;
}

export namespace ShipmentApprovedEvent {
  export type InputTuple = [shipmentId: BytesLike, sender: AddressLike];
  export type OutputTuple = [shipmentId: string, sender: string];
  export interface OutputObject {
    shipmentId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipmentDeliveredEvent {
  export type InputTuple = [shipmentId: BytesLike, receiver: AddressLike];
  export type OutputTuple = [shipmentId: string, receiver: string];
  export interface OutputObject {
    shipmentId: string;
    receiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipmentDispatchedEvent {
  export type InputTuple = [shipmentId: BytesLike, sender: AddressLike];
  export type OutputTuple = [shipmentId: string, sender: string];
  export interface OutputObject {
    shipmentId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipmentRequestedEvent {
  export type InputTuple = [
    shipmentId: BytesLike,
    batchId: BytesLike,
    receiver: AddressLike,
    sender: AddressLike,
    unitStart: BigNumberish,
    unitEnd: BigNumberish,
    quantity: BigNumberish
  ];
  export type OutputTuple = [
    shipmentId: string,
    batchId: string,
    receiver: string,
    sender: string,
    unitStart: bigint,
    unitEnd: bigint,
    quantity: bigint
  ];
  export interface OutputObject {
    shipmentId: string;
    batchId: string;
    receiver: string;
    sender: string;
    unitStart: bigint;
    unitEnd: bigint;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplyEventRecordedEvent {
  export type InputTuple = [
    unitId: BytesLike,
    eventType: BigNumberish,
    actor: AddressLike,
    locationHash: BytesLike
  ];
  export type OutputTuple = [
    unitId: string,
    eventType: bigint,
    actor: string,
    locationHash: string
  ];
  export interface OutputObject {
    unitId: string;
    eventType: bigint;
    actor: string;
    locationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShipmentLedger extends BaseContract {
  connect(runner?: ContractRunner | null): ShipmentLedger;
  waitForDeployment(): Promise<this>;

  interface: ShipmentLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveShipment: TypedContractMethod<
    [shipmentId: BytesLike],
    [void],
    "nonpayable"
  >;

  confirmDelivery: TypedContractMethod<
    [shipmentId: BytesLike],
    [void],
    "nonpayable"
  >;

  dispatchShipment: TypedContractMethod<
    [shipmentId: BytesLike],
    [void],
    "nonpayable"
  >;

  getUnitEvents: TypedContractMethod<
    [unitId: BytesLike],
    [ShipmentLedger.SupplyEventStructOutput[]],
    "view"
  >;

  recordSupplyEvent: TypedContractMethod<
    [
      unitId: BytesLike,
      eventType: BigNumberish,
      locationHash: BytesLike,
      senderConfirmed: boolean,
      receiverConfirmed: boolean
    ],
    [void],
    "nonpayable"
  >;

  requestShipment: TypedContractMethod<
    [
      shipmentId: BytesLike,
      batchId: BytesLike,
      unitStart: BigNumberish,
      unitEnd: BigNumberish,
      sender: AddressLike,
      quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  shipments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        shipmentId: string;
        batchId: string;
        unitStart: bigint;
        unitEnd: bigint;
        sender: string;
        receiver: string;
        quantity: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveShipment"
  ): TypedContractMethod<[shipmentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<[shipmentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dispatchShipment"
  ): TypedContractMethod<[shipmentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getUnitEvents"
  ): TypedContractMethod<
    [unitId: BytesLike],
    [ShipmentLedger.SupplyEventStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordSupplyEvent"
  ): TypedContractMethod<
    [
      unitId: BytesLike,
      eventType: BigNumberish,
      locationHash: BytesLike,
      senderConfirmed: boolean,
      receiverConfirmed: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestShipment"
  ): TypedContractMethod<
    [
      shipmentId: BytesLike,
      batchId: BytesLike,
      unitStart: BigNumberish,
      unitEnd: BigNumberish,
      sender: AddressLike,
      quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "shipments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        shipmentId: string;
        batchId: string;
        unitStart: bigint;
        unitEnd: bigint;
        sender: string;
        receiver: string;
        quantity: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ShipmentApproved"
  ): TypedContractEvent<
    ShipmentApprovedEvent.InputTuple,
    ShipmentApprovedEvent.OutputTuple,
    ShipmentApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ShipmentDelivered"
  ): TypedContractEvent<
    ShipmentDeliveredEvent.InputTuple,
    ShipmentDeliveredEvent.OutputTuple,
    ShipmentDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "ShipmentDispatched"
  ): TypedContractEvent<
    ShipmentDispatchedEvent.InputTuple,
    ShipmentDispatchedEvent.OutputTuple,
    ShipmentDispatchedEvent.OutputObject
  >;
  getEvent(
    key: "ShipmentRequested"
  ): TypedContractEvent<
    ShipmentRequestedEvent.InputTuple,
    ShipmentRequestedEvent.OutputTuple,
    ShipmentRequestedEvent.OutputObject
  >;
  getEvent(
    key: "SupplyEventRecorded"
  ): TypedContractEvent<
    SupplyEventRecordedEvent.InputTuple,
    SupplyEventRecordedEvent.OutputTuple,
    SupplyEventRecordedEvent.OutputObject
  >;

  filters: {
    "ShipmentApproved(bytes32,address)": TypedContractEvent<
      ShipmentApprovedEvent.InputTuple,
      ShipmentApprovedEvent.OutputTuple,
      ShipmentApprovedEvent.OutputObject
    >;
    ShipmentApproved: TypedContractEvent<
      ShipmentApprovedEvent.InputTuple,
      ShipmentApprovedEvent.OutputTuple,
      ShipmentApprovedEvent.OutputObject
    >;

    "ShipmentDelivered(bytes32,address)": TypedContractEvent<
      ShipmentDeliveredEvent.InputTuple,
      ShipmentDeliveredEvent.OutputTuple,
      ShipmentDeliveredEvent.OutputObject
    >;
    ShipmentDelivered: TypedContractEvent<
      ShipmentDeliveredEvent.InputTuple,
      ShipmentDeliveredEvent.OutputTuple,
      ShipmentDeliveredEvent.OutputObject
    >;

    "ShipmentDispatched(bytes32,address)": TypedContractEvent<
      ShipmentDispatchedEvent.InputTuple,
      ShipmentDispatchedEvent.OutputTuple,
      ShipmentDispatchedEvent.OutputObject
    >;
    ShipmentDispatched: TypedContractEvent<
      ShipmentDispatchedEvent.InputTuple,
      ShipmentDispatchedEvent.OutputTuple,
      ShipmentDispatchedEvent.OutputObject
    >;

    "ShipmentRequested(bytes32,bytes32,address,address,uint32,uint32,uint256)": TypedContractEvent<
      ShipmentRequestedEvent.InputTuple,
      ShipmentRequestedEvent.OutputTuple,
      ShipmentRequestedEvent.OutputObject
    >;
    ShipmentRequested: TypedContractEvent<
      ShipmentRequestedEvent.InputTuple,
      ShipmentRequestedEvent.OutputTuple,
      ShipmentRequestedEvent.OutputObject
    >;

    "SupplyEventRecorded(bytes32,uint8,address,bytes32)": TypedContractEvent<
      SupplyEventRecordedEvent.InputTuple,
      SupplyEventRecordedEvent.OutputTuple,
      SupplyEventRecordedEvent.OutputObject
    >;
    SupplyEventRecorded: TypedContractEvent<
      SupplyEventRecordedEvent.InputTuple,
      SupplyEventRecordedEvent.OutputTuple,
      SupplyEventRecordedEvent.OutputObject
    >;
  };
}
